Repository kubernetes-sigs/cluster-capacity, pull requests merged in 2020-08, with the labels that each got.

#123 Introduce e2e tests
  Makefile
  test/e2e/e2e_test.go
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#124 Add missing hack/kind_config.yaml
  hack/kind_config.yaml
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#126 Update api-operations.md
  doc/api-operations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
